const test=require('node:test'),assert=require('node:assert/strict');
const D=require('../renderer/cloud-display'),{Viewer3DGL}=require('../renderer/webgl-viewer');
function viewer(){const v=Object.create(Viewer3DGL.prototype);v.render=()=>{};v._notifyCloudChanged=()=>{};v.base=[{points:true,count:3,pos:new Float32Array([0,-2,0, 0,0,0, 0,3,0])}];v.bbox={mn:[-1,-2,-1],mx:[1,3,1]};v.section={on:false,min:[0,0,0],max:[1,1,1]};v._cloudDisplay={pointSize:1,opacity:1,min:-2,max:3,palette:0,hideOutside:false};v._cloudRecord={sourceName:'C:\\scan\\здание.las',sourceCount:102641770};return v;}
test('File names: Windows, POSIX, unicode; no guessed scan names',()=>{assert.equal(D.fileName('C:\\scan\\здание.las'),'здание.las');assert.equal(D.fileName('/cloud/a.ply'),'a.ply');assert.equal(D.fileName(''),'Облако без имени');});
test('Range endpoints, negative heights and constant-height cloud',()=>{assert.deepEqual(D.range(-70.79,127.53),[-70.79,127.53]);assert.equal(D.normalize(4,4,4),.5);assert.equal(D.normalize(-2,-2,3),0);assert.equal(D.normalize(3,-2,3),1);});
test('Reject inverted or nonfinite height range, preserve previous state',()=>{const v=viewer();for(const r of [[3,2],[NaN,2],[0,Infinity]])assert.throws(()=>v.setCloudHeightRange(...r),RangeError);assert.equal(v._cloudDisplay.min,-2);});
test('Point size and opacity clamp without zero fallback bug',()=>{const v=viewer();assert.equal(v.setCloudOpacity(0),0);assert.equal(v.setCloudOpacity(10),1);assert.equal(v.setCloudOpacity(-1),0);assert.equal(v.setCloudPointSize(10),10);assert.equal(v.setCloudPointSize(.1),1);assert.throws(()=>v.setCloudOpacity(NaN));assert.throws(()=>v.setCloudPointSize(Infinity));});
test('Histogram bins include both endpoints exactly',()=>{const p=new Float32Array([0,-2,0,0,0,0,0,3,0]);assert.deepEqual(D.histogram(p,[-2,3],5).bins,[1,0,1,0,1]);});
test('Histogram skips nonfinite heights and handles empty/flat input',()=>{assert.equal(D.histogram(new Float32Array([0,NaN,0,0,0,0]),[0,0]).sampled,1);assert.equal(D.histogram(new Float32Array(),[0,0]).sampled,0);assert.equal(D.histogram(new Float32Array([0,2,0]),[2,2],4).bins[2],1);});
test('Histogram work bounded independently of large source count',()=>{const p=new Float32Array(600003);const h=D.histogram(p,[0,1],64,1000);assert.ok(h.sampled<=1000);assert.equal(h.approximate,true);assert.equal(h.bins.reduce((a,b)=>a+b,0),h.sampled);});
test('Palette endpoints and midpoint exact',()=>{assert.deepEqual(D.color(0,'rainbow'),[0,0,.5]);assert.deepEqual(D.color(.5,'rainbow'),[.5,1,.5]);assert.deepEqual(D.color(1,'rainbow'),[.5,0,0]);assert.deepEqual(D.color(.25,'gray'),[.25,.25,.25]);assert.deepEqual(D.color(1,'warm'),[1,0,0]);});
test('Source count never substituted for resident/display count',()=>{const v=viewer(),i=v.getCloudInfo();assert.equal(i.sourceCount,102641770);assert.equal(i.loadedCount,3);i.bounds.mn[0]=999;assert.equal(v.bbox.mn[0],-1);});
test('Height clipping intersects existing section, inclusive endpoints',()=>{const v=viewer();v.setColorMode('elev');v.setCloudHeightRange(0,3);v.setCloudHideOutside(true);assert.deepEqual(v._clipBounds(),{mn:[-1,0,-1],mx:[1,3,1]});assert.equal(v._pointInClip(0),false);assert.equal(v._pointInClip(1),true);assert.equal(v._pointInClip(2),true);v.section.on=true;v.section.max[1]=.8;assert.equal(v._clipBounds().mx[1],2);assert.equal(v._pointInClip(2),false);});
test('RGB disables height filter without losing configured range',()=>{const v=viewer();v.setColorMode('elev');v.setCloudHeightRange(1,2);v.setCloudHideOutside(true);v.setColorMode('rgb');assert.equal(v._pointInClip(0),true);assert.equal(v._cloudDisplay.min,1);});
test('Invisible and zero-opacity points cannot be selected',()=>{const v=viewer();v.setCloudOpacity(0);assert.deepEqual(v._clipFilter([0,1,2]),[]);assert.equal(v._pickGPU(0,0),null);assert.equal(v._pickPoint(0,0),null);v.setCloudOpacity(1);v.setCloudVisible(false);assert.deepEqual(v._clipFilter([0,1,2]),[]);});
test('Mesh replaces cloud without stale height filter/metadata',()=>{const v=viewer();v.setColorMode('elev');v.setCloudHideOutside(true);v._cloudRecord=null;assert.equal(v._heightFilter(),false);assert.equal(v.getCloudInfo(),null);});

test("Unknown original file count remains unknown",()=>{const v=viewer();v._cloudRecord.sourceCount=null;assert.equal(v.getCloudInfo().sourceCount,null);assert.equal(v.getCloudInfo().loadedCount,3);});
