/* BIM Twin v1213 — direct ViewCube, ribbon actions, cancellation, unified progress */
(()=>{'use strict';
 const $=id=>document.getElementById(id), q=(s,p=document)=>p.querySelector(s), qa=(s,p=document)=>[...p.querySelectorAll(s)];
 const fmt=s=>{s=Math.max(0,Math.round(s||0));const m=Math.floor(s/60),r=s%60;return m?`${m}:${String(r).padStart(2,'0')}`:`0:${String(r).padStart(2,'0')}`};
 let seq=0,active=null;
 function progressDom(){let m=$('lxProgressModal');if(m)return m;m=document.createElement('div');m.id='lxProgressModal';m.setAttribute('role','dialog');m.setAttribute('aria-modal','true');m.setAttribute('aria-live','polite');m.innerHTML='<div class="lx-progress-card"><div class="lx-progress-title">Обработка</div><div class="lx-progress-msg">Подготовка…</div><div class="lx-progress-track"><div class="lx-progress-fill"></div></div><div class="lx-progress-meta"><b class="lx-progress-pct">0%</b><span class="lx-progress-time">Прошло 0:00 · осталось —</span></div><div class="lx-progress-actions"><button type="button" class="lx-progress-cancel">Отмена</button></div></div>';document.body.append(m);return m}
 function beginProgress(label){const m=progressDom(),token=++seq,start=performance.now();let frac=0,done=false,timer=0;const title=q('.lx-progress-title',m),msg=q('.lx-progress-msg',m),fill=q('.lx-progress-fill',m),pct=q('.lx-progress-pct',m),time=q('.lx-progress-time',m),cancel=q('.lx-progress-cancel',m);title.textContent=String(label||'Обработка').replace(/…+$/,'');msg.textContent=label||'Подготовка…';m.classList.add('open');document.documentElement.classList.add('lx-operation-busy');
  const paint=()=>{const elapsed=(performance.now()-start)/1000;const eta=frac>.025&&frac<1?elapsed*(1-frac)/frac:null;fill.style.width=`${Math.round(frac*100)}%`;pct.textContent=`${Math.round(frac*100)}%`;time.textContent=`Прошло ${fmt(elapsed)} · осталось ${eta==null?'—':fmt(eta)}`};
  const close=()=>{if(done)return;done=true;clearInterval(timer);if(active&&active.token===token)active=null;m.classList.remove('open');document.documentElement.classList.remove('lx-operation-busy')};
  const stop=function(){frac=1;paint();setTimeout(close,180)};stop.token=token;stop.set=(f,text)=>{if(done)return;frac=Math.max(0,Math.min(1,Number(f)||0));if(text)msg.textContent=text;paint()};stop.text=text=>{if(text)msg.textContent=text};stop.cancel=()=>{window.dispatchEvent(new CustomEvent('lx-progress-cancel',{detail:{token,label}}));cancelAll();close()};cancel.onclick=stop.cancel;active={token,stop};timer=setInterval(paint,500);paint();return stop }
 window.__lxProgress={begin:beginProgress,get active(){return active}};
 function setView(name,btn){const v=window.__viewer||window.__lxViewer;if(v&&typeof v.setStandardView==='function')v.setStandardView(name);qa('.lx-cube-direct .lx-face').forEach(x=>x.classList.toggle('active',x===btn))}
 function buildCube(){let old=q('.lx-cube');if(!old||old.classList.contains('lx-cube-coordinates'))return;const cube=old.cloneNode(false);cube.className='lx-cube lx-cube-direct lx-cube-coordinates';cube.dataset.workspace='1';cube.removeAttribute('role');cube.removeAttribute('tabindex');cube.title='Куб видов: нажмите грань или координатную ось';cube.innerHTML=`<svg class="lx-viewcube-svg" viewBox="0 0 128 128" aria-label="Куб стандартных видов">
  <g class="lx-vface lx-vtop" data-view="top" role="button" tabindex="0" aria-label="Вид сверху"><polygon points="35,34 68,16 103,35 68,54"/><text x="68" y="36">ВЕРХ</text></g>
  <g class="lx-vface lx-vfront" data-view="front" role="button" tabindex="0" aria-label="Вид спереди"><polygon points="35,34 68,54 68,91 35,70"/><text x="52" y="65">ФАС</text></g>
  <g class="lx-vface lx-vright" data-view="right" role="button" tabindex="0" aria-label="Вид справа"><polygon points="68,54 103,35 103,72 68,91"/><text x="86" y="65">ПРАВО</text></g>
  <g class="lx-vcenter" data-view="iso" role="button" tabindex="0" aria-label="Изометрический вид"><circle cx="68" cy="54" r="5"/><title>Изометрия</title></g>
  <g class="lx-axis lx-axis-x"><line x1="68" y1="92" x2="116" y2="98"/><circle data-view="right" cx="116" cy="98" r="8"/><text x="113" y="102">+X</text><circle data-view="left" cx="19" cy="86" r="8"/><line x1="35" y1="70" x2="19" y2="86"/><text x="15" y="90">−X</text></g>
  <g class="lx-axis lx-axis-y"><line x1="68" y1="16" x2="68" y2="5"/><circle data-view="top" cx="68" cy="7" r="8"/><text x="64" y="10">+Y</text><line x1="68" y1="92" x2="68" y2="116"/><circle data-view="bottom" cx="68" cy="117" r="8"/><text x="64" y="120">−Y</text></g>
  <g class="lx-axis lx-axis-z"><line x1="35" y1="70" x2="16" y2="109"/><circle data-view="front" cx="16" cy="109" r="8"/><text x="12" y="113">+Z</text><line x1="103" y1="35" x2="116" y2="18"/><circle data-view="back" cx="116" cy="18" r="8"/><text x="112" y="22">−Z</text></g>
 </svg>`;cube.addEventListener('click',e=>{const hit=e.target.closest?.('[data-view]');if(!hit)return;e.preventDefault();e.stopImmediatePropagation();setView(hit.dataset.view,hit)},true);cube.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.view){e.preventDefault();setView(e.target.dataset.view,e.target)}},true);old.replaceWith(cube);const menu=$('viewCube');if(menu)menu.hidden=true;const pop=$('uiViews');if(pop)pop.remove()}
 const actionDefs=[['section','Сечение объекта'],['measure','Измерить'],['scan','Скан → BIM'],['bim','BIM 1:1']];
 function ensureActionGroup(){const host=q('.toolbar .tbtns');if(!host)return;let group=$('lxRibbonActions');if(!group){group=document.createElement('div');group.id='lxRibbonActions';group.className='tgroup';group.dataset.lxtab='home';group.innerHTML='<div class="tgrow"></div><div class="tglabel">Инструменты 3D</div>';host.append(group)}const row=q('.tgrow',group),dock=q('.ui-vpbar');const pool=dock?qa('button',dock):[];actionDefs.forEach(([kind,label])=>{const b=pool.find(x=>x.dataset.vpKind===kind||((x.textContent||'').replace(/\s+/g,' ').includes(label)));if(!b||row.contains(b))return;b.classList.add('lx-bigbtn','tbtn');b.dataset.lxbig='1';['position','left','right','top','bottom','background','background-color','color','border','border-color','box-shadow','opacity','margin'].forEach(k=>b.style.removeProperty(k));row.append(b)});const tab=q('#lxTabs .lx-tab.active');group.dataset.lxhidden=(tab?.dataset.tab||'home')==='home'?'0':'1';if(dock&&!dock.children.length)dock.remove()}
 function exportIcon(label){const t=String(label||'').split(/\s|\(/)[0].replace(/[^A-Za-z0-9]/g,'').slice(0,4).toUpperCase()||'FILE';return `<span class="lx-bic lx-export-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M6 3h8l4 4v14H6zM14 3v5h4M12 10v7m0 0-3-3m3 3 3-3"/></svg><small>${t}</small></span>`}
 function exportButton(label,fn){const b=document.createElement('button');b.type='button';b.className='tbtn lx-bigbtn lx-export-btn';b.dataset.lxbig='1';b.dataset.uiDecorated='1';b.innerHTML=exportIcon(label)+`<span class="lx-blabel">${label}</span>`;b.title=label;b.setAttribute('aria-label',label);b.addEventListener('click',fn);return b}
 function exportGroup(id,label){const host=q('.toolbar .tbtns');let g=$(id);if(g)return q('.tgrow',g);g=document.createElement('div');g.id=id;g.className='tgroup lx-export-group';g.dataset.lxtab='export';g.innerHTML=`<div class="tgrow"></div><div class="tglabel">${label}</div>`;host.append(g);return q('.tgrow',g)}
 function selectRibbonTab(name){qa('#lxTabs .lx-tab').forEach(t=>{const on=t.dataset.tab===name;t.classList.toggle('active',on);t.setAttribute('aria-selected',String(on))});qa('.toolbar .tgroup').forEach(g=>g.dataset.lxhidden=g.dataset.lxtab===name?'0':'1')}
 function buildExportRibbon(){const tabs=$('lxTabs'),api=window.__lxSmartSave;if(!tabs||!q('.toolbar .tbtns')||!api)return false;let tab=$('lxExportTab');if(!tab){tab=document.createElement('button');tab.type='button';tab.id='lxExportTab';tab.className='lx-tab';tab.dataset.tab='export';tab.textContent='Экспорт';tab.setAttribute('role','tab');tab.setAttribute('aria-selected','false');tab.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();window.__lxWorkspace?.exitTools?.();selectRibbonTab('export')},true);tabs.append(tab)}
  const save=exportGroup('lxExportSave','Сохранение');if(!save.children.length){save.append(exportButton('Сохранить',()=>api.save({})),exportButton('Сохранить как',()=>api.save({askPath:true})),exportButton('Автосохранение',()=>{const cur=api.status?.().intervalMin||0;const seq=[0,1,2,5,10],next=seq[(seq.indexOf(cur)+1)%seq.length];api.setInterval(next)}))}
  const cloud=exportGroup('lxExportCloud','Облако точек'),bim=exportGroup('lxExportBim','BIM-модель');if(!cloud.children.length&&!bim.children.length)(api.formats||[]).forEach(f=>(f.kind==='bim'?bim:cloud).append(exportButton(f.label,()=>api.exportAs(f.id))));
  qa('.lx-smart-save').forEach(x=>x.remove());return true }
 let projectHistoryBusy=false;
 function syncProjectHistoryRibbon(){const ps=window.BimProjectState,undo=$('lxProjectUndo'),redo=$('lxProjectRedo');if(undo)undo.disabled=projectHistoryBusy||!(ps&&ps.canUndo);if(redo)redo.disabled=projectHistoryBusy||!(ps&&ps.canRedo)}
 function runProjectHistoryRibbon(api,method){if(projectHistoryBusy)return;projectHistoryBusy=true;syncProjectHistoryRibbon();Promise.resolve().then(()=>api[method]()).catch(error=>{try{console.warn('[project-history] action failed',error)}catch(_){}}).finally(()=>{projectHistoryBusy=false;syncProjectHistoryRibbon()})}
 function buildProjectHistoryRibbon(){const host=q('.toolbar .tbtns'),api=window.__lxSmartSave;if(!host||!api)return false;let group=$('lxProjectHistoryGroup');if(!group){group=document.createElement('div');group.id='lxProjectHistoryGroup';group.className='tgroup lx-project-history-group';group.dataset.lxtab='home';group.innerHTML='<div class="tgrow"></div><div class="tglabel">История проекта</div>';host.insertBefore(group,host.firstChild)}const row=q('.tgrow',group);function add(id,cls,label,title,fn){let b=$(id);if(!b){b=exportButton(label,fn);b.id=id;b.title=title;b.setAttribute('aria-label',title);b.classList.add(cls);row.append(b)}return b}add('lxProjectUndo','lx-project-undo','Отменить','Отменить последнее сохранённое изменение проекта',()=>runProjectHistoryRibbon(api,'undoProjectState'));add('lxProjectRedo','lx-project-redo','Повторить','Повторить отменённое изменение проекта',()=>runProjectHistoryRibbon(api,'redoProjectState'));add('lxDraftHistory','lx-draft-history','Черновики','Показать и восстановить версии автосохранения',()=>api.openAutosaveHistory());const active=q('#lxTabs .lx-tab.active'),hidden=(active&&active.dataset.tab||'home')==='home'?'0':'1';if(group.dataset.lxhidden!==hidden)group.dataset.lxhidden=hidden;if(!window.__lxProjectHistoryRibbonBound){window.__lxProjectHistoryRibbonBound=true;['bim-project-state-ready','bim-project-state-saved','bim-project-state-restored','bim-project-state-error'].forEach(name=>window.addEventListener(name,syncProjectHistoryRibbon))}syncProjectHistoryRibbon();return true}
 function removeXgrids(){qa('#tsSplatXgrids,#vtXgrids,[data-tool="xgrids"],.xgrids-button').forEach(x=>x.remove())}
 const modeIds=new Set(['btnMeasure','vtMeasure','btnSection','vtSection','vtEdit','vtWalk','vtTour','lxObjPick','lxSectBtn']);
 function modeButton(target){const b=target.closest?.('button');if(!b)return null;const text=(b.textContent||'').toLowerCase();return modeIds.has(b.id)||/(измер|правк|прогул|сечен|выделить объект)/.test(text)?b:null}
 function buttonModeActive(b){return b.classList.contains('lx-mode-active')||b.classList.contains('on')||b.getAttribute('aria-pressed')==='true'}
 let modeEpoch=0;
 function engineModeActive(){const v=window.__viewer||window.__lxViewer;return !!(v&&(v.measuring||v.editSelect||v.walk||v.tour||v.lod||(v.section&&v.section.on)))||!!window.__lxDraw?.active}
 function isModeActive(b){return buttonModeActive(b)||engineModeActive()}
 function clearModeMarks(){const xs=new Set([...qa('.lx-mode-active'),...qa('#lxLtbar button.active')]);['btnMeasure','vtMeasure','btnSection','vtSection','vtEdit','vtWalk','vtTour','lxObjPick','lxSectBtn'].forEach(id=>{const b=$(id);if(b)xs.add(b)});xs.forEach(x=>{x.classList.remove('lx-mode-active','on');if(x.matches('#lxLtbar button'))x.classList.remove('active');x.setAttribute('aria-pressed','false')})}
 function cancelAll(){modeEpoch++;try{window.__lxWorkspace?.exitTools()}catch(e){}const v=window.__viewer||window.__lxViewer;try{v?.setMeasuring?.(false);v?.setMeasure?.(false);v?.setEditSelect?.(false);v?.setWalk?.(false);v?.setTour?.(false);v?.setSection?.(false);if(v?.lod)v?.setLOD?.(false);v?.clearSelection?.()}catch(e){}try{window.__lxObjectExtract?.close?.()}catch(e){}try{window.__lxObjectInspector?.close?.()}catch(e){}try{if(window.__lxDraw?.active)window.__lxDrawUI?.deactivate?.(true)}catch(e){}clearModeMarks();['measureBar','measureListPanel','measureReadout','editBar','tourBar','sectionPanel','sectionRange','qualityBar','lxSectionControls'].forEach(id=>{const e=$(id);if(e)e.style.display='none'});window.dispatchEvent(new CustomEvent('lx-tools-cancelled'))}
 function installModeExit(){window.addEventListener('click',e=>{const b=modeButton(e.target);if(!b)return;if(buttonModeActive(b)){e.preventDefault();e.stopImmediatePropagation();cancelAll();return}if(engineModeActive())cancelAll();const token=modeEpoch;setTimeout(()=>{if(token===modeEpoch&&isModeActive(b)){b.classList.add('lx-mode-active');b.setAttribute('aria-pressed','true')}},0)},true);window.addEventListener('keydown',e=>{if(e.key!=='Escape')return;const tag=e.target?.tagName;if(/INPUT|TEXTAREA|SELECT/.test(tag)&&!active)return;e.preventDefault();if(active)active.stop.cancel();else cancelAll()},true)}
 function bridgeProgress(){if(!window.__pcTools||window.__pcTools.beginProgress?.__v1213)return false;const f=label=>beginProgress(label);f.__v1213=true;window.__pcTools.beginProgress=f;return true}
 function patchPly(){const p=window.PlyToSplat;if(!p||p.__v1213||typeof p.convert!=='function')return;p.__v1213=true;const original=p.convert.bind(p);p.convert=async(buf,opts={})=>{const stop=beginProgress('PLY → 3DGS');const cb=opts.progress;try{return await original(buf,{...opts,progress:(n,m)=>{stop.set((Number(n)||0)/100,m);cb?.(n,m)}})}finally{stop()}}}
 function init(){buildCube();ensureActionGroup();buildExportRibbon();buildProjectHistoryRibbon();removeXgrids();bridgeProgress();patchPly();const mo=new MutationObserver(()=>{buildCube();ensureActionGroup();buildExportRibbon();buildProjectHistoryRibbon();removeXgrids();bridgeProgress();patchPly()});mo.observe(document.body,{childList:true,subtree:true});window.addEventListener('lx-cloud-loaded',()=>setTimeout(()=>window.__viewer?._resize?.(),80))}
 installModeExit();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,300));else setTimeout(init,300);window.addEventListener('bim-app-ready',()=>setTimeout(init,80),{once:true});
})();
