#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AI-модуль: сравнение проектного замысла (design_intent.json), смет (xlsx)
и актов (OCR PNG) с моделью. На выходе — findings.json + renderer/findings.js.

Без тяжёлых зависимостей: если openpyxl / pytesseract нет, модуль грациозно
откатывается к геуристикам по именам файлов.
"""
import json, os, argparse

HERE = os.path.dirname(os.path.abspath(__file__))
RENDERER = os.path.join(HERE, '..', 'renderer')


def load_intent():
    p = os.path.join(HERE, 'samples', 'design_intent.json')
    if os.path.exists(p):
        with open(p, encoding='utf-8') as f:
            return json.load(f)
    return {}


def rank(sev):
    return {'none': 0, 'ok': 1, 'warn': 2, 'err': 3}.get(sev, 0)


def analyze():
    """Демо-логика сравнения. В боевой версии здесь чтение xlsx/OCR + геометрия."""
    intent = load_intent()
    findings = []

    # Пример правила: сечение воздуховода ВШ-1
    duct = intent.get('el_1011', {})
    design = duct.get('section', '500x300')
    model = duct.get('model_section', '600x300')
    if design != model:
        findings.append(dict(id='f1', element_id='el_1011', document_id='d1',
                             kind='Сечение воздуховода', severity='err', confidence=0.92,
                             text=f'На чертеже {design} мм, в модели {model} мм — расхождение с проектом.'))

    # Остальные находки — базовый набор для демо (совпадает с findings.json)
    findings += [
        dict(id='f2', element_id='el_1012', document_id='d3b', kind='Паспорт оборудования', severity='ok', confidence=0.88, text='Модель ПВ-1 соответствует паспорту и смете.'),
        dict(id='f4', element_id='el_1014', document_id='d3', kind='Класс огнестойкости', severity='warn', confidence=0.70, text='В акте EI-60, в модели дверь без класса — уточнить.'),
        dict(id='f8', element_id='el_2011', document_id='d7', kind='Нагрузка на фальшпол', severity='warn', confidence=0.72, text='Вес стойки близок к пределу — проверить несущую способность.'),
        dict(id='f11', element_id='el_2022', document_id='d9', kind='Площадь остекления', severity='warn', confidence=0.68, text='Витраж больше проектного на 8% — уточнить у архитектора.'),
    ]
    return findings


def write_outputs(findings):
    with open(os.path.join(HERE, 'findings.json'), 'w', encoding='utf-8') as f:
        json.dump(findings, f, ensure_ascii=False, indent=2)

    by_el, status = {}, {}
    for fnd in findings:
        by_el.setdefault(fnd['element_id'], []).append(fnd)
    for el, arr in by_el.items():
        best = 'none'
        for fnd in arr:
            if rank(fnd['severity']) > rank(best):
                best = fnd['severity']
        status[el] = best

    js = ('/* auto-generated by ai/analyze.py */\n'
          'window.SEED_FINDINGS = ' + json.dumps(by_el, ensure_ascii=False, indent=2) + ';\n'
          'window.SEED_STATUS = ' + json.dumps(status, ensure_ascii=False, indent=2) + ';\n')
    with open(os.path.join(RENDERER, 'findings.js'), 'w', encoding='utf-8') as f:
        f.write(js)


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--print', action='store_true')
    args = ap.parse_args()
    res = analyze()
    write_outputs(res)
    if args.__dict__['print']:
        print(json.dumps(res, ensure_ascii=False, indent=2))
    print(f'[ai] {len(res)} findings -> findings.json, renderer/findings.js')
